### ISSUE TITLE
button icons don't show

### ISSUE THREAD

**Issue by hannesdelbeke** [hannesdelbeke/unreal-plugin-python-script-editor#1]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3758308/232478189-53a641d5-541d-43fa-9f27-c5e6299a6442.png">

**Comment by hannesdelbeke** [comment]
buttons are there but dont show images.
likely some kind of stylesheet hookup or resource not found issues

**Comment by hannesdelbeke** [comment]
- [ ] merge in fix from https://github.com/leixingyu/unrealScriptEditor
- [ ] verify it's fixed.
- [ ] reply to issue on original repo if fixed

**Comment by free8011** [comment]
buttons are there but dont show images in UE5.
5.2.1: 
you can fix it. update code to >> entry.set_icon('OutputLogStyle', 'DebugConsole.Icon')
